### ISSUE TITLE
Trainning Dataset

### ISSUE THREAD

**Issue by lian131622** [casus/pi-ddpm#1]
Many thanks to the great work!

I am having problem with generating the training dataset. Since I am not very much familar with the term used in the OTF and I am not quite sure about what kernels are. Could you please provide some small dataset so that we can try to run the model?

Many thanks!

**Comment by nanoxas** [comment]
Hi, I'm glad that you are interested in our work. The OTF we used is the Arnison-Sheppard model. We used the implementation provided by this repo https://github.com/david-hoffman/pyotf

About the dataset here you can find the biosr dataset we used in the paper in this link. 

https://drive.google.com/drive/folders/1ZMLAZo4AGX4QASEyd3MGf8LE2B_Bne04

After you can use the lightbased_microscopy_psf function to generate synthetic data and train the models.

Hope this helps!

**Comment by ManuBN786** [comment]
How to open the BioSR dataset parts like "bio_sr_part_00" ?

What tool should I use ?

I can only open the test "biosr_ds_test.npz" easily as it's in .npz

Please provide more details

**Comment by ManuBN786** [comment]
Thank you for a quick reply!

I did  'cat bio_sr_part* > biosr_ds_train.npz'  for  bio_sr_part_00 & bio_sr_part_01.

But numpy says it's not zipped.

Is it needed to zip all the parts to get a proper .npz file?
![Screenshot from 2024-08-08 18-14-28](https://github.com/user-attachments/assets/20532d02-4d73-428a-b017-f7dbf9b6dfa6)

**Comment by nanoxas** [comment]
You need to download all the part files put them into one folder and that will generate the correct npz.

**Comment by ManuBN786** [comment]
Thanks a lot !

It worked perfectly !!

If I face further issues while training, I will raise it .

**Comment by ManuBN786** [comment]
X_on_disk = np.load('data/BioSR/train_npy/biosr_ds_train/x.npy', mmap_mode='r')
Y_on_disk = np.load('data/BioSR/train_npy/biosr_ds_train/y.npy', mmap_mode='r')

This is used to read large .npy files.
